# Generated by Django 4.1.2 on 2022-11-19 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='descriotion',
            new_name='description',
        ),
    ]
